### ISSUE TITLE
Accept parser doesn't work with mirage-xen

### ISSUE THREAD

**Issue by juanchanco** [mirage/ocaml-cohttp#464] opened 2016-03-23 17:36 UTC
accept_parser.mly processes floats using "float_of_string" which seems to compile down to a call to strtod, which is not implemented in the Mini-OS that mirage-xen runs on top of, so a unikernel hitting that crashes.
The problem is at line 45:

    param :
    | SEMI TOK EQUAL QS { Kv ($2, S $4) }
    | SEMI TOK EQUAL TOK {
    if $2="q" then try Q (truncate (1000.*.(float_of_string $4)))
        with Failure "float_of_string" -> raise Parsing.Parse_error
    else Kv ($2, T $4)
    }

This changed (scanning in integers, then converting) _seemed_ to work (didn't fail) but has not been tested much:

    param :
    | SEMI TOK EQUAL QS { Kv ($2, S $4) }
    | SEMI TOK EQUAL TOK {
    if $2="q" then try Q (truncate (1000.*.
        (Scanf.sscanf $4 "%i.%i" (fun q d -> (float_of_int q) /. (float_of_int d)))))
        with Failure "float_of_string" -> raise Parsing.Parse_error
    else Kv ($2, T $4)
    }

I uncovered this in a project that uses Webmachine in a unikernel. At a certain point, Webmachine calls

    let acceptable = MyAccept.encodings (Some "identity;q=1.0,*;q=0.5") in
    ...

which triggers the error when deploy in xen.

**Comment by hannesm** [comment] 2016-03-28 20:15
the root cause is a missing `strtod` in mirage on xen (see https://github.com/mirage/mirage-platform/issues/118)

**Comment by ansiwen** [comment] 2016-04-29 20:17
same problem here: https://bpaste.net/show/607e55d45508

so, will this be fixed in cohttp? what can we do about it? I need a solution, but I'm not sure how it's going to be fixed. I could help.

**Comment by avsm** [comment] 2016-04-30 11:34
I've started a tree with a 4.03 runtime port, so I'll look at strod while doing that.

**Comment by avsm** [comment] 2016-05-02 23:26
works in mirage/mirage-platform#165

**Closed** 2016-05-02 23:39 UTC
