### ISSUE TITLE
Installing cohttp.0.21.0

### ISSUE THREAD

**Issue by rleonid** [mirage/ocaml-cohttp#512] opened 2016-11-09 07:33 UTC
On 4.03.0 switch:

```
#=== ERROR while installing cohttp.0.21.0 =====================================#
# opam-version 1.2.2
# os           darwin
# command      make PREFIX=/Users/lr/.opam/4.03.0
# path         /Users/lr/.opam/4.03.0/build/cohttp.0.21.0
# compiler     4.03.0
# exit-code    2
# env-file     /Users/lr/.opam/4.03.0/build/cohttp.0.21.0/cohttp-13723-ffb3fd.env
# stdout-file  /Users/lr/.opam/4.03.0/build/cohttp.0.21.0/cohttp-13723-ffb3fd.out
# stderr-file  /Users/lr/.opam/4.03.0/build/cohttp.0.21.0/cohttp-13723-ffb3fd.err
### stdout ###
# [...]
# File "caml_startup", line 1:
# Error: Error during linking
# Command exited with code 2.
# + /Users/lr/.opam/4.03.0/bin/ocamlopt.opt unix.cmxa -I /Users/lr/.opam/4.03.0/lib/ocamlbuild /Users/lr/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /Users/lr/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "myocamlbuild.ml", line 518, characters 43-62:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
# File "myocamlbuild.ml", line 531, characters 51-70:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
### stderr ###
# W: Cannot find source file matching module 'cohttp' in library cohttp
# E: Failure("Command ''/Users/lr/.opam/4.03.0/bin/ocamlbuild' lib/cohttp.cma lib/cohttp.cmxa lib/cohttp.a lib/cohttp.cmxs top/cohttp_top.cma top/cohttp_top.cmxa top/cohttp_top.a top/cohttp_top.cmxs lwt-core/cohttp_lwt.cma lwt-core/cohttp_lwt.cmxa lwt-core/cohttp_lwt.a lwt-core/cohttp_lwt.cmxs lwt/cohttp_lwt_unix.cma lwt/cohttp_lwt_unix.cmxa lwt/cohttp_lwt_unix.a lwt/cohttp_lwt_unix.cmxs bin/cohttp_server_lwt.native bin/cohttp_proxy_lwt.native bin/cohttp_curl_lwt.native examples/doc/client_lwt.native examples/doc/server_lwt.native -tag debug -classic-display' terminated with error code 10")
# make: *** [build] Error 1
```

**Comment by avsm** [comment] 2016-11-09 13:43
This is a new one -- what is your operating system and architecture, and how did you install OCaml?  It is failing to link an executable. Do any other binaries work?

**Comment by rleonid** [comment] 2016-11-09 15:39
Sorry for the incomplete report. Mac, newest Sierra version. With brew.

When trying to build in the opam build directory, it turns out it is a linking error:
```
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
```

adding `-cclib -L/usr/local/opt/openssl/lib` to the `cohttp_server_lwt.native` build command succeeded.

**Comment by rleonid** [comment] 2016-11-09 15:42
OCaml was `brew`'ed opam and then `4.03.0` switch.

**Comment by avsm** [comment] 2016-11-09 16:04
try "opam depext -ui ssl cohttp" to install the brew dependencies as well

**Comment by rleonid** [comment] 2016-11-09 18:15
That fails on the latest `ssl` which I've already `pin`ed and patched like [here](https://github.com/savonet/ocaml-ssl/issues/22). The issue though remains for building `cohttp` itself as I still have to pass link arguments for `cohttp_server_lwt.native`. So now I have to figure out how to get the right environment variables passed through `oasis`'s build.

This message from `brew install openssl` is pertinent for a long term solution:
```
Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```

**Comment by rleonid** [comment] 2016-11-09 18:17
I guess the offender is`conduit`. Is there a way to build it specifically to use the all `OCaml` TLS implementation?

**Comment by rleonid** [comment] 2016-11-09 20:05
I still can't figure out how to pass the necessary linker commands to `cohttp` build. For example, even adding `true: cclib(-L/usr/local/opt/openssl/lib)` to `_tags` is ignored. I'm really unfamiliar with the steps necessary to modify the `oasis` build.

**Comment by dbuenzli** [comment] 2017-01-24 18:13
I have the same problem (I recently upgraded to sierra aswell): 

```
> opam depext -ui ssl cohttp
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - openssl
#  - pkg-config
# All required OS packages found.
# Now letting OPAM install the packages
[NOTE] Package ssl is already installed (current version is 0.5.3).
The following actions will be performed:
  ∗  install cohttp 0.21.0
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[cohttp] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of cohttp failed at "make PREFIX=/Users/dbuenzli/.opam/4.03.0".
Processing  1/1: [cohttp: ocamlfind remove]
#=== ERROR while installing cohttp.0.21.0 =====================================#
# opam-version 1.2.2
# os           darwin
# command      make PREFIX=/Users/dbuenzli/.opam/4.03.0
# path         /Users/dbuenzli/.opam/4.03.0/build/cohttp.0.21.0
# compiler     4.03.0
# exit-code    2
# env-file     /Users/dbuenzli/.opam/4.03.0/build/cohttp.0.21.0/cohttp-45036-1872ec.env
# stdout-file  /Users/dbuenzli/.opam/4.03.0/build/cohttp.0.21.0/cohttp-45036-1872ec.out
# stderr-file  /Users/dbuenzli/.opam/4.03.0/build/cohttp.0.21.0/cohttp-45036-1872ec.err
### stdout ###
# [...]
# File "caml_startup", line 1:
# Error: Error during linking
# Command exited with code 2.
# + /Users/dbuenzli/.opam/4.03.0/bin/ocamlopt.opt unix.cmxa -I /Users/dbuenzli/.opam/4.03.0/lib/ocamlbuild /Users/dbuenzli/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /Users/dbuenzli/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "myocamlbuild.ml", line 518, characters 43-62:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
# File "myocamlbuild.ml", line 531, characters 51-70:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
### stderr ###
# W: Cannot find source file matching module 'cohttp' in library cohttp
# E: Failure("Command ''/Users/dbuenzli/.opam/4.03.0/bin/ocamlbuild' lib/cohttp.cma lib/cohttp.cmxa lib/cohttp.a lib/cohttp.cmxs top/cohttp_top.cma top/cohttp_top.cmxa top/cohttp_top.a top/cohttp_top.cmxs lwt-core/cohttp_lwt.cma lwt-core/cohttp_lwt.cmxa lwt-core/cohttp_lwt.a lwt-core/cohttp_lwt.cmxs lwt/cohttp_lwt_unix.cma lwt/cohttp_lwt_unix.cmxa lwt/cohttp_lwt_unix.a lwt/cohttp_lwt_unix.cmxs js/cohttp_lwt_xhr.cma js/cohttp_lwt_xhr.cmxa js/cohttp_lwt_xhr.a js/cohttp_lwt_xhr.cmxs bin/cohttp_server_lwt.native bin/cohttp_proxy_lwt.native bin/cohttp_curl_lwt.native examples/doc/client_lwt.native examples/doc/server_lwt.native -tag debug -classic-display' terminated with error code 10")
# make: *** [build] Error 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install cohttp 0.21.0
No changes have been performed
```
Is there's a way out it's quite annoying as it's needed for `opam-publish`. I also try to pin on `dev-repo` without success.

**Comment by dbuenzli** [comment] 2017-01-24 19:31
So here's a workaround: 

```
 LIBRARY_PATH=/usr/local/opt/openssl/lib opam install cohttp
```

I suspect the real issue is https://github.com/savonet/ocaml-ssl/issues/30, however it has been closed and marked as resolved by `opam` (?).

**Comment by avsm** [comment] 2017-01-26 22:14
@dbuenzli: I can't reproduce this on my Sierra machine. Do you have files similar to this in your installation?

```
$ ls -la /usr/lib/libcrypto.*
-rwxr-xr-x  1 root  wheel  2043536 13 Jan 07:13 /usr/lib/libcrypto.0.9.7.dylib
-rwxr-xr-x  1 root  wheel  2681408 13 Jan 07:14 /usr/lib/libcrypto.0.9.8.dylib
-rw-r--r--  1 root  wheel  4209728 13 Jan 07:13 /usr/lib/libcrypto.35.dylib
lrwxr-xr-x  1 root  wheel       21  3 Dec 00:45 /usr/lib/libcrypto.dylib -> libcrypto.0.9.8.dylib
```

I guess these might have been left over from an upgrade, and my system is using the existing libcrypto.

**Comment by dbuenzli** [comment] 2017-01-26 22:22
> @dbuenzli: I can't reproduce this on my Sierra machine. Do you have files similar to this in your installation?

Yes. 

```
> ls -al /usr/lib/libcrypto.*
-rwxr-xr-x  1 root  wheel  2043536 Dec 10 10:04 /usr/lib/libcrypto.0.9.7.dylib*
-rwxr-xr-x  1 root  wheel  2681408 Dec 10 10:01 /usr/lib/libcrypto.0.9.8.dylib*
-rw-r--r--  1 root  wheel  4209728 Dec 10 10:02 /usr/lib/libcrypto.35.dylib
lrwxr-xr-x  1 root  wheel       21 Jan 14 10:52 /usr/lib/libcrypto.dylib@ -> libcrypto.0.9.8.dylib
```

**Comment by dbuenzli** [comment] 2017-01-26 22:31
So I tried to remove `opam-ssl` and then `cohttp` installs fine. The culprit is really `opam-ssl` as I can't reinstall it (fails with `configure: error: Cannot find libssl.`)

**Comment by samoht** [comment] 2017-01-27 08:59
I confirm that installing `ssl` in a fresh switch on macOS is broken:

```
#=== ERROR while installing ssl.0.5.3 =========================================#
# opam-version 1.2.2
# os           darwin
# command      sh -exc ./configure --prefix /Users/thomas/.opam/ssl CPPFLAGS="$CPPFLAGS -I/opt/local/include -I/usr/local/opt/openssl/include"
# path         /Users/thomas/.opam/ssl/build/ssl.0.5.3
# compiler     system (4.04.0)
# exit-code    1
# env-file     /Users/thomas/.opam/ssl/build/ssl.0.5.3/ssl-39582-03b1a4.env
# stdout-file  /Users/thomas/.opam/ssl/build/ssl.0.5.3/ssl-39582-03b1a4.out
# stderr-file  /Users/thomas/.opam/ssl/build/ssl.0.5.3/ssl-39582-03b1a4.err
### stdout ###
# [...]
# checking for ocamldep... /usr/local/bin/ocamldep
# checking for ocamllex... /usr/local/bin/ocamllex
# checking for ocamlyacc... /usr/local/bin/ocamlyacc
# checking for ocamldoc... /usr/local/bin/ocamldoc
# checking for ocamlmktop... /usr/local/bin/ocamlmktop
# checking for gcc... (cached) gcc
# checking whether we are using the GNU C compiler... (cached) yes
# checking whether gcc accepts -g... (cached) yes
# checking for gcc option to accept ISO C89... (cached) none needed
# checking for SSL_new in -lssl... no
### stderr ###
# + ./configure --prefix /Users/thomas/.opam/ssl 'CPPFLAGS= -I/opt/local/include -I/usr/local/opt/openssl/include'
# configure: error: Cannot find libssl.
```

**Comment by dsheets** [comment] 2017-01-27 12:00
I'm not sure what `opam-ssl` is but I can install `ssl.0.5.3` and `publish.0.3.3` on a fresh install of macOS 10.12 just fine. Perhaps it's an XCode version or macOS upgrade issue? I don't have XCode installed in this VM.

**Comment by avsm** [comment] 2017-01-27 12:02
I can also install `ssl.0.5.3` fine. @samoht, can you try `xcode-select --install` and see if that helps?

**Comment by samoht** [comment] 2017-01-27 12:14
@avsm so `xcode-select --install` indeed resolved the issue: I can install `ssl` in a fresh switch after running that command.

**Comment by samoht** [comment] 2017-01-27 12:14
(which is a bit strange as I already had xcode installed, but as @dsheets pointed out, maybe I had a too old version)

**Comment by avsm** [comment] 2017-01-27 12:18
It doesn't always autoupgrade the tools, unfortunately. @dbuenzli -- could you also confirm if `xcode-select --install` resolves your issue?  Can make this a post-messages hint on osx if so.

**Comment by dbuenzli** [comment] 2017-01-27 12:25
> @dbuenzli -- could you also confirm if xcode-select --install resolves your issue?

This (which said it would install the cli tools) *and* a new terminal did it. So the culprit seems to be the macOS upgrade and xcode.

**Comment by rleonid** [comment] 2017-02-21 22:29
For posterity, `xcode-select --install` resulted in linking errors:
```
Undefined symbols for architecture x86_64:
  "_TLSv1_1_client_method", referenced from:
      _ocaml_ssl_create_context in libssl_stubs.a(ssl_stubs.o)
  "_TLSv1_1_method", referenced from:
      _ocaml_ssl_create_context in libssl_stubs.a(ssl_stubs.o)
  "_TLSv1_1_server_method", referenced from:
      _ocaml_ssl_create_context in libssl_stubs.a(ssl_stubs.o)
  "_TLSv1_2_client_method", referenced from:
      _ocaml_ssl_create_context in libssl_stubs.a(ssl_stubs.o)
  "_TLSv1_2_method", referenced from:
      _ocaml_ssl_create_context in libssl_stubs.a(ssl_stubs.o)
  "_TLSv1_2_server_method", referenced from:
      _ocaml_ssl_create_context in libssl_stubs.a(ssl_stubs.o)
```
but installing cohttp with `LIBRARY_PATH=/usr/local/opt/openssl/lib` worked for me afterwards.

**Closed** 2018-07-07 04:05 UTC
