### ISSUE TITLE
Getting the remote IP in a Client.call

### ISSUE THREAD

**Issue by SGrondin** [mirage/ocaml-cohttp#234] opened 2015-01-21 01:11 UTC
From reading the source, it doesn't seem to be possible because the connection isn't exposed at any time to the caller. It would also be great to be able to know what IP Client.call tried to connect to when it raised an exception.

Is there a way to get around those limitations? I think it's a necessary feature for an HTTP library to have.

Thanks a lot and good job on building cohttp, it's a great tool.

**Comment by dsheets** [comment] 2015-01-21 09:57
This is the client equivalent of #188.

**Comment by rgrinberg** [comment] 2015-01-26 01:07
Yes this is rather important. I don't think this feature justifies breaking the API though so we should bolt on some other type of call that includes this information.

**Comment by mseri** [comment] 2021-04-18 19:11
Closing as duplicate of #188. Added to the list of issues to explore for further releases

**Closed** 2021-04-18 19:12 UTC
