### ISSUE TITLE
String of body empty after an rdf query

### ISSUE THREAD

**Issue by ArnaudParant** [mirage/ocaml-cohttp#121] opened 2014-04-18 15:12 UTC
Hello,

I'm trying to use cohttp to bind an rdf store.
After submiting my request I receive the status 200, thus the server well received the request and gave a response. But when I print the string of the body, it's empty.

I tried to do the request on a browser, it works by downloading the response and the console wrote:
```
Resource interpreted as Document but transferred with MIME type application/sparql-results+xml
```

I tried also with curl on a term, it correctly print the response:
```
$ curl "http://localhost:8000/sparql/?query=SELECT%20%3Fs%20%3Fp%20%3Fo%20WHERE%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D"
<?xml version="1.0"?>
<sparql xmlns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="s"/>
    <variable name="p"/>
    <variable name="o"/>
  </head>
  <results>
    <result>
      <binding name="s"><uri>http://pumgrana.com/content/detail/52780cbdc21477f7aa5b9107</uri></binding>
      <binding name="p"><uri>http://pumgrana.com/content/detail/52780d55c21477f7aa5b9108</uri></binding>
      <binding name="o"><literal>Part of</literal></binding>
    </result>
  </results>
</sparql>
```

Here is my code:
```ocaml
let url = "http://localhost:8000/sparql/"
let query = "SELECT ?s ?p ?o WHERE { ?s ?p ?o }" 

let print_response url query =
  let uri = Uri.of_string (url ^ "?query=" ^ query) in 
  match_lwt (Cohttp_lwt_unix.Client.get uri) with
    | None -> Lwt_io.printl "Error"
    | Some (response, body) ->
      let headers = Cohttp.Response.headers response in
      Cohttp.Header.iter (fun n c -> print_endline (n ^ ":" ^ (List.hd c))) headers;
      let st = Cohttp.Response.status response in
      print_endline ("status:" ^ (string_of_int (Cohttp.Code.code_of_status st)));
      lwt bs = Cohttp_lwt_body.string_of_body body in
      Lwt_io.printl ("body:[" ^ bs ^ "]")

let _ = 
  let p = print_response url query in
  Lwt_main.run p
```

Am I doing something wrong ?
Or maybe it's due of the mine using ?

Thanks in advance,
Arnaud,

**Comment by rgrinberg** [comment] 2015-02-28 22:00
Closing this as this is just a dupe of #124

**Closed by rgrinberg** 2015-02-28 22:00 UTC
Labels: API
