### ISSUE TITLE
Compilation fails in 4.06.0 - Unbound module Cohttp.String_io

### ISSUE THREAD

**Issue by ghost** [mirage/ocaml-cohttp#584] opened 2017-11-13 22:45 UTC
```
[ERROR] The compilation of cohttp-lwt failed at "jbuilder build -p cohttp-lwt -j 4".
#=== ERROR while installing cohttp-lwt.0.99.0 =================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p cohttp-lwt -j 4
# path         /home/x/.opam/4.06.0/build/cohttp-lwt.0.99.0
# compiler     4.06.0
# exit-code    1
# env-file     /home/x/.opam/4.06.0/build/cohttp-lwt.0.99.0/cohttp-lwt-8604-e7966f.env
# stdout-file  /home/x/.opam/4.06.0/build/cohttp-lwt.0.99.0/cohttp-lwt-8604-e7966f.out
# stderr-file  /home/x/.opam/4.06.0/build/cohttp-lwt.0.99.0/cohttp-lwt-8604-e7966f.err
### stderr ###
# [...]
#          ppx cohttp-lwt/src/cohttp_lwt.pp.ml
#          ppx cohttp-lwt/src/cohttp_lwt.pp.mli
#          ppx cohttp-lwt/src/cohttp_lwt_body.pp.mli
#          ppx cohttp-lwt/src/string_io_lwt.pp.mli
#     ocamldep cohttp-lwt/src/cohttp_lwt.dependsi.ocamldep-output
#     ocamldep cohttp-lwt/src/cohttp_lwt.depends.ocamldep-output
#       ocamlc cohttp-lwt/src/string_io_lwt.{cmi,cmti} (exit 2)
# (cd _build/default && /home/x/.opam/4.06.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/x/.opam/4.06.0/lib/base -I /home/x/.opam/4.06.0/lib/base/caml -I /home/x/.opam/4.06.0/lib/base/shadow_stdlib -I /home/x/.opam/4.06.0/lib/base64 -I /home/x/.opam/4.06.0/lib/bytes -I /home/x/.opam/4.06.0/lib/cohttp -I /home/x/.opam/4.06.0/lib/fieldslib -I /home/x/.opam/4.06.0/lib/lwt -I /home/x/.opam/4.06.0/lib/ocaml -I /home/x/.opam/4.06.0/lib/re -I /home/x/.opam/4.06.0/lib/result -I /home/x/.opam/4.06.0/lib/sexplib -I /home/x/.opam/4.06.0/lib/sexplib/0 -I /home/x/.opam/4.06.0/lib/stringext -I /home/x/.opam/4.06.0/lib/uri -no-alias-deps -I cohttp-lwt/src -o cohttp-lwt/src/string_io_lwt.cmi -c -intf cohttp-lwt/src/string_io_lwt.pp.mli)
# File "cohttp-lwt/src/string_io_lwt.mli", line 26, characters 16-36:
# Error: Unbound module Cohttp.String_io
```

**Comment by IrisJinyanZheng** [comment] 2017-11-19 02:32
I also have the same error!!!

**Comment by shayne-fletcher** [comment] 2017-11-28 19:20
And me. My colleague tells me that it is not 4.06 specific however.

**Comment by mseri** [comment] 2018-10-20 12:15
Closing as I was not able to reproduce. It's likely a bug in an old version of jbuilder. Feel free to re-open it if you still have this issue

**Closed by mseri** 2018-10-20 12:15 UTC
