### ISSUE TITLE
Cohttp server refuses to die

### ISSUE THREAD

**Issue by darioteixeira** [mirage/ocaml-cohttp#505] opened 2016-09-11 18:17 UTC
I want a Cohttp Lwt server thread to kill itself on command. Here's the code:

``` ocaml
let (stop, stopper) = Lwt.wait () in
let _ = Cohttp_lwt_unix.Server.create ~stop ~mode:(`TCP (`Port 8080)) callback in
... (* do some stuff *)
Lwt.wakeup stopper ()
```

Essentially I'm creating a `stop` thread and its `stopper` wakener with `Lwt.wait`.  Then I pass the `stop` thread to `Cohttp_lwt_unix.Server.create`, do some processing, and when I intend for the server to die I just call `Lwt.wakeup` on the `stopper` wakener.

Anyway, this doesn't work.  Did I misunderstand the mechanism or is this an actual bug?

**Comment by jerith** [comment] 2017-01-28 12:17
This was caused by mirage/ocaml-conduit#110 which is fixed in conduit 1.14.0 and later.

**Closed** 2021-04-19 09:31 UTC
Labels: Bug
