### ISSUE TITLE
Out-of-heap pointer

### ISSUE THREAD

**Issue by mknaack** [mirage/ocaml-cohttp#964] opened 2023-01-19 21:18 UTC
I get a out-of-heap pointer when running the client example from the frontpage.

I have an example of the problem here: [https://github.com/mknaack/cosmos-nnp](https://github.com/mknaack/cosmos-nnp)

Running the docker file will get the out-of-heap pointer.

**Comment by avsm** [comment] 2023-01-20 15:57
Thanks for the very accurate reproduction mechanism.  The out of heap pointer looks like it comes from the ocaml-ssl bindings, which was fixed in their trunk in https://github.com/savonet/ocaml-ssl/pull/98.  I'll close this issue as it's not a matter for cohttp, but perhaps @anmonteiro might be able to cut a new release of ocaml-ssl that is compatible with OCaml 5.0. /cc @kit-ty-kate 

As a workaround until that release you can either:
- add `opam pin add ssl --dev` to your dockerfile; or
- remove `lwt_ssl` and replace with `tls` for the pure OCaml TLS stack

**Closed by avsm** 2023-01-20 15:57 UTC

**Comment by anmonteiro** [comment] 2023-01-20 19:45
Thanks for the ping. I'll cut a release this weekend.
