### ISSUE TITLE
Yet another reproducible bug, insane for simple request. 

### ISSUE THREAD

**Issue by fxfactorial** [mirage/ocaml-cohttp#454] opened 2016-01-20 04:45 UTC
Say you have a server 

```ocaml

....
    Cohttp_lwt_unix.Server.make ~callback ()
    |> Cohttp_lwt_unix.Server.create ~mode:(`TCP (`Port 5000)) 
```
where call back just always calls respond_string, 
Then you get this insane result.

<img width="650" alt="screen shot 2016-01-19 at 8 45 05 pm" src="https://cloud.githubusercontent.com/assets/3036816/12440170/97ad7ae8-beed-11e5-917f-2a917bac9973.png">

**Comment by rgrinberg** [comment] 2016-01-20 06:17
Would id be possible to give a complete and reproducible example? Screenshots and rhetoric are nice and all but a complete example would help us fix this much faster.

**Comment by fxfactorial** [comment] 2016-01-20 06:23
@rgrinberg Sorry you're right. I just feel like I've been filling out bug tickets literally every day lately. 

```ocaml
#require "cohttp.lwt"

let status_server = Uri.of_string "http://localhost:5000"

let () =
  let callback _ _ _ =
    let body = "Hello World" in
    Cohttp_lwt_unix.Server.respond_string ~status:`OK ~body ()
  in
  let server = Cohttp_lwt_unix.Server.make ~callback () in
  Cohttp_lwt_unix.Server.create ~mode:(`TCP (`Port 5000)) server
  |> Lwt_main.run
```

Then in utop

```ocaml
Cohttp_lwt_unix.Client.get (Uri.of_string "http://localhost:5000");;
```

You'll get: 

```ocaml
Exception: Unix.Unix_error (Unix.ECONNREFUSED, "connect", "").
```

Then try with `127.0.0.1` and everything is great.

```ocaml
Cohttp_lwt_unix.Client.get (Uri.of_string "http://127.0.0.1:5000");;
- : Cohttp.Response.t * Cohttp_lwt_body.t =                                                                                               ({Cohttp.Response.encoding = Cohttp.Transfer.Fixed 11L; headers = <abstr>; version = `HTTP_1_1; status = `OK; flush = false},              `Stream <abstr>)
```

**Comment by rgrinberg** [comment] 2016-01-20 06:34
Looks like this is a lwt only problem. You can reproduce this very easily with:

```
# the lwt backend fails
$ ./cohttp_curl_lwt.native 'http://localhost:5000'
# while the async backend succeeds
./cohttp_curl_async.native 'http://localhost:5000'
```

I have a hunch that this is a problem with conduit. Possibly has something to do with:

https://github.com/rgrinberg/ocaml-conduit/blob/master/lib/resolver_lwt_unix.mli

**Comment by fxfactorial** [comment] 2016-01-20 06:47
Yea, looks like a good hunch.

**Comment by avsm** [comment] 2016-01-20 13:53
Interesting, looks like `/etc/hosts` resolution is failing for some reason in the Lwt resolver.  Possibly `getaddrinfo` vs `gethostbyname`

**Comment by talex5** [comment] 2016-01-20 14:02
Most likely it's resolving "localhost" to "::1" (i.e. IPv6), but you're listening only on IPv4.

**Comment by edwintorok** [comment] 2016-01-20 14:06
I actually had this in my `/etc/gai.conf` which forced IPv4 addresses to come first, which is why I couldn't reproduce this:
```
precedence ::ffff:0:0/96  100
```

Could conduit be improved to try to connect to all IPs if first one from resolver fails though?

**Comment by avsm** [comment] 2016-01-20 14:43
> Could conduit be improved to try to connect to all IPs if first one from resolver fails though?

Definitely a good idea. I'd like to expose address selection strategies in conduit somehow, with a sensible default like iterate-until-success.  Multipath TCP encourages parallel selection of addresses and tracking of endpoint latency.

**Comment by rgrinberg** [comment] 2016-05-01 19:15
Closing because this is a conduit issue.

**Closed by rgrinberg** 2016-05-01 19:15 UTC
